weather_sat_links:
    - Weather
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=weather&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=noaa&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=goes&FORMAT=csv
earth_observation_sat_links:
    - Earth Observation
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=resource&FORMAT=csv                       
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=sarsat&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=dmc&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=tdrss&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=argos&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=planet&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=spire&FORMAT=csv
communications_sat_links:
    - Communications
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=intelsat&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=ses&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=iridium&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=iridium-NEXT&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=starlink&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=oneweb&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=orbcomm&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=globalstar&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=swarm&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=amateur&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=x-comm&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=other-comm&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=satnogs&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=gorizont&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=raduga&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=molniya&FORMAT=csv
navigation_sat_links:
    - Navigation
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=gnss&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=gps-ops&FORMAT=csv          
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=glo-ops&FORMAT=csv                 
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=galileo&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=beidou&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=sbas&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=nnss&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=musson&FORMAT=csv
scientific_sat_links:
    - Scientific
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=science&FORMAT=csv             
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=geodetic&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=engineering&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=education&FORMAT=csv
miscellaneous_sat_links:
    - Miscellaneous
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=military&FORMAT=csv                      
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=radar&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=cubesat&FORMAT=csv
    - https://celestrak.com/NORAD/elements/gp.php?GROUP=other&FORMAT=csv
